var recommendName = [
  "Jericho Nathanael Chrisnanta",
  "Iftala Zahri Sukmana",
  "Dana Saputra",
  "Nashwan Rasyid M",
  "Nabilah Atika Rahma",
  "Ardhika Krishna Wijaya",
  "Yehezkiella Felicia Jeis Timbulong",
  "Made Daryl Adi Nugraha ",
  "Anthony Setiawan ",
  "Muhammad Ariandra Dwiratama",
  "Muhammad Farhan Dzulfikar",
  "Roofiif Alria Dzakwan",
  "Thariq Ivan Anendar",
  "Rafhi Sadipta",
  "Arsya Dewi Lathifa ",
  "Aria Nalini Farzana ",
  "Valentino Reswara Ajiputra",
  "Mirza Zaki Rafii ",
  "Nathaniel Ryo Kurniadi",
  "Andreas Reynard Samsico",
  "Muhammad Nabil Akhtar Raya Amoriza",
  "Andika Rahman Teja",
  "Firania Putri Harsanti",
  "Jesse Robinson Junior Simanjuntak",
  "Wahid Badar Abiddin ",
  "Abyan Bismar Alfayed",
  "Decya Giovanni",
  "Fadhl Akmal Madany",
  "Nayla Arina ",
  "Muhammad Hafidz Harridil Mahali",
  "Faren Haseena Arif",
  "Gilang Gunawan Saputra",
  "Malvin Leonardo Hartanto",
  "Bintang Wibi Hanoraga",
  "Razan Abdullah",
  "Nicklaus Natanael S Gurukinayan",
  "Mikha Gracia Sugiono",
  "Rafli Syahputra Pane",
  "Muhammad Wafi Zaki Hanif ",
  "Genta Putra Prayoga ",
  "Karina Rahmawati",
  "Keanu Fortuna Taufan",
  "Tunas Abdi Pranata",
  "Wildan Fauzy Maulana Hasyim ",
  "Steven Gerard Nathaniel Lekatompessy",
  "Edward Samuel Susanto",
  "Muhammad Rayyaan Fatikhahur Rakhim",
  "Yanuar Eka Pramudya ",
  "Lucky Santoso",
  "Pelangi Masita Wati ",
  "Muhammad Syarif Hidayatullah",
  "Ainun Nadhifah Syamsiyah",
  "Chalvin Reza Farrel",
  "Audrey Sasqhia Wijaya",
  "AMANDA ILLONA FARREL",
  "Fairuuz Azmi Firas ",
  "Muhammad Abdurrahman Faiz",
  "Surya Fadli Alamsyah",
  "Muhammad Rifqi Ma’ruf ",
  "Moch. Avin",
  "Putri Meyliya Rachmawati",
  "Nadia Evi Nathania",
  "Nerisa Afiani",
  "Samuel Josefano Kaloh",
  "Muhammad Abhyasa Santoso ",
  "Syalbia Noor Rahmah",
  "Areta Athayayumna Arwaa",
  "Muhammad Aulia Triatmono",
  "Zefanya Teguh Foyd Silalahi ",
  "Muhammad Reza Octavianto",
  "Fawwaz Abdulloh Al-Jawi ",
  "Surya Prima Pradana ",
  "Iffa Amalia Sabrina",
  "Shafa Kirana Mulia",
  "Naufal Ahmad Fahreza",
  "Ihsan Adhika Rahadian",
  "Ralfazza Rajariandhana",
  "Franshel Tranetha",
  "MOH. AZRIL ADDIA ANANDA",
  "Taib Izzat Samawi",
  "Fayza Aqila Bachtiar",
  "Wirandito Sarwono",
  "Hafidzuddin Rizqy Amirullah",
  "Rayhan Fathurrahman Zata Amani",
  "Muhammad Izzul Sinar Mahadhika",
  "Giandra Raihan Nayottama",
  "Muhammad Luthfi Zafir",
  "Maheswari Parisya Putri",
  "Radian Try Darmawan",
  "Putra Adam Sultansyah",
  "Hassan Mohammad Mahsun",
  "Riyanda Cavin Sinambela",
  "Lalu Aldo Wadagraprana",
  "MARCO MARCELLO HUGO",
  "Hilmi Fawwaz Sa'ad",
  "Achmad Fajri Sudrajab ",
  "Dian Kusumawati ",
  "Dzuhrillah Hendraines",
  "Nafilah Yuga Zhafir ",
  "Samuel Arthur Gamalliel",
  "Fellyla Fiorenza Wilianto",
  "Joanes Don Bosco Bhramantyo",
  "Robin Hannan",
  "Mikhael Abie Saputra",
  "Mohammad Idris Arif Budiman ",
  "Birhasani Raka Abiansyah",
  "Unedo Viery Kristenzky Tampubolon ",
  "Richard Halomoan Sitanggang ",
  "Maruli Gilbert Cristopel Hutagaol ",
  "Willyam Brordus",
  "Abiyu Ramadhan Kiesly ",
  "Zelvan Abdi Wijaya",
  "Azarel Grahandito Adi",
  "Naufal Khairul Rizky",
  "Fathurazka Gamma Syuhada",
  "Arkan Arsalan Amanullah",
  "Lathiifah Nabiila Bakhtiar",
  "Ahmad Tsaqif Imtinan",
  "Rumaisha Afrina",
  "Jonathan Purba",
  "Mu'aafii Putra Ramadhan",
  "Zharga Prayata Zainal",
  "Davin Fisabilillah Reynard Putra",
  "Farrel Akmalazmi Nugraha",
  "Jeremy James",
  "Koresy Samuel Parlinggoman Nainggolan",
  "Jevon Tama Aristo Manurung",
  "Fahmi Anhar Fatwaddin",
  "Fadhiil Hanif Rizqullah",
  "Rafli Dzulhaikal",
  "Meylina Tesa Hapsari ",
  "Muhammad Irsyad Habibi",
  "Helsa Sriprameswari Putri",
  "Adnan Abdullah Juan",
  "Rakha Fathin Izzan Consetta",
  "JAMALUDDIN",
  "Muhammad Aqil Farrukh",
  "LATHIFAH SAHDA",
  "Fairna Mustika Hermafidhanti",
  "Mohammad Hanif Furqan Aufa Putra",
  "Wendy Gata Ramadhani ",
  "Mochammad Zharif Asyam Marzuqi",
  "Abillidya Nofianto Putri",
  "Danish Austin Wicaksana",
  "Dhia Auzie Cantika",
  "Ivan Fairuz Adinata",
  "Rayhan Maulana Akbar ",
  "Bimantara Putra Ernandra ",
  "Billy Jonathan",
  "Gilang Kista Ramadhan",
  "Aloysius deDeo Darmo Susanto",
  "Bryant Nathaniel Tanujaya",
  "Aloysius Juan Farrel Lumentut",
  "Brendan Timothy Mannuel",
  "Muhammad Ivan Ardianadi Afiat",
  "Fawwas Aldy Nurramdhan Kaisar",
  "Ahmad Alvin Jauhari ",
  "Amadhea Trizza Audina",
  "BIANCA SHAUMMAYA ARYAN",
  "Pradipta Arya Daniswara",
  "Adyuta Prajahita Murdianto",
  "Fatiya Izzati ",
  "Muhammad Alif Satriadhi",
  "Ignatius Ida Bagus Abimanyu",
  "Rhenaldy Chandra",
  "Ahmad Fatih Ramadhani",
  "Alief Gilang Permana Putra",
  "Nyoman Satyawikrama Upadhana",
  "Ahmad Fadhilah Mappisara",
  "Andi Aliyah Nur Inayah Pattoza",
  "Ike Norfaize",
  "Muhammad Nabil Fadhil",
  "Alvin Vincent Oswald Reba",
  "Hilmy Septian Nursyekha",
  "Muhammad Choirun Ni'am",
  "Andina Safitri Innayah",
  "Aulia Daffa Rahmani",
  "Arundaya Pratama Nurhasan ",
  "Aditya Situmorang",
  "M Fadhil Abhista Daniswara",
  "Farhan Widyanto Wibowo",
  "I Putu Raditya Partha Wijaya",
  "Muhammad Ihsan Al Khwaritsmi",
  "Yoga Firman Syahputra",
  "Tamara Jovanka",
  "Irfan Ridhana",
  "Putu Indra Mahendra",
  "Muhammad Gesang Ridho Widigdo",
  "Ricardo Supriyanto",
  "Faa'iz Haikal Hilmi",
  "Muhammad Mirza Ralfie Prasetyo ",
  "Delai Resgista Setyawan",
  "Almira Fidela Soehartanto Putri ",
  "Daffa Zimraan Hassan",
  "Muhammad Fayyadh Rahinda",
  "Muhammad Althaf Arianto",
  "Gavrila Nirwasita",
  "Ranto Bastara Hamonangan Sitorus",
  "Adrian Aziz Santoso ",
  "dwiyana yudha prawira",
  "Vidiawan Nabiel Arrasyid",
  "Haikal Athallarik",
  "Sri Kusumo Fathoni Rais",
  "Furstin Aprilavia Putri",
  "Athaya Rohadatul Yaqutah",
  "Muhammad Detri Abdul Fikar",
  "Aurelia Natasya Putri",
  "Mohamad Valdi Ananda Tauhid",
  "Muhammad Danis Hadriansyah ",
  "Bayza Nawaz Axata ",
  "Richo Yudha Kurniawan",
  "Azizah Elok Harvianti",
  "Alvin Rayhaan Ardhana",
  "Izzat Aji Androfaza",
  "Nadya Saraswati Putri ",
  "Gayu Baruwa",
  "Stevanza Gian Maheswara",
  "Almira Raisa Izzatina",
  "Mochammad Irham Maulana",
  "Revy Pramana",
  "Farel Hanif Andaru ",
  "Akma Aufa Hamzi",
  "Jeremia Raphael Agusty",
  "Aryasatya Wiryawan",
  "Syarif Sanad",
  "Farrell Matthew Lim",
  "Chalwat Sanubari",
  "Muhammad Bimatara Indianto",
  "Daffa Diandra Rizky Aghnia",
  "Adrian aryasatya Putra Tjindarbumi",
  "Reynaldi Neo Ramadhani",
  "Rafli Raihan Pramudya",
  "Ariq Javier Ramadhani Rahim ",
  "Garda Sudarmanto",
  "Muhammad Nabihan Alzam",
  "Yosua Hares",
  "Hardy Tee",
  "Aditya Rizki Muhammad",
  "Yasmin Putri S",
  "Muhammad Iqbal Ramadhan ",
  "Muhammad Alfan Mahdi",
  "Johannes Daniswara Pratama",
  "Muhammad Hafizh Najwan Noor",
  "Joseph Marcell Gultom",
  "Arya Gading Prinandika",
  "Aulia Putri Salsabila",
  "Daru Fadhilah Nahdi",
  "Hanif Al Fattah",
  "Farra Sabiilah Annajiihah",
  "Winston Juliand Sitranata",
  "Nabhyla Niagara Rannuan",
  "Athaya Coulava Putradhana",
  "Al Dhihya Gaza Halim Putra",
  "Nouval Royhan Akbar",
  "Nisrina Salma Robbani",
  "Muhammad Irfan Hakim",
  "Rezqy Belva Rihan Poernomo",
  "Faiq Lidan Baihaqi",
  "Agnes Priscilla Sekartaji Hadikusuma",
  "Nuril Qolbi Zam Zami",
  "Alendra Rafif Athaillah",
  "Allen Keyo Handika",
  "Eldintaro Farrandi Arisdani",
  "Dimas Athallah Zaki",
  "Muhammad Farras Arif Fadhila ",
  "Muhammad Fahmi Syahputra",
  "Faiz Syawaludin Asril",
  "Fanza Khairan Pratama",
  "Ardafa Aqilla Ahsan",
  "Muhammad rafi budi purnama",
  "Giobert Boyhosea Panjaitan",
  "Fauzan Dzikri Rabbani",
  "Wu Alfred Hardy",
  "Fairuz Fuadi",
  "Jhonatan Christopher Lundu Simorangkir",
  "Kaleb Dimitrio",
  "Tabina Callistadya",
  "Dimas Ahmad Fahreza",
  "Adelia Putri Kamaski",
  "Geovannie deef pilph wamo",
];

var dosenList = [
  "Ir. Siti Rochimah, MT., Ph.D.",
  "Prof. Daniel Oranova Siahaan, S.Kom., M.Sc. PD.Eng.",
  "Sarwosri, S.Kom., MT.",
  "Dr. Umi Laili Yuhana S.Kom., M.Sc.",
  "Rizky Januar Akbar, S.Kom., M.Eng.",
  "Prof. Tohari Ahmad, S.Kom., M.IT., Ph.D.",
  "Bagus Jati Santoso, S.Kom., Ph.D.",
  "Hudan Studiawan, S.Kom., M.Kom., Ph.D.",
  "Dr. Baskoro Adi P., S.Kom.,M.Kom.",
  "Ary Mazharuddin Shiddiqi, S.Kom., M.Comp.Sc., Ph.D",
  "Prof. Dr. Eng. Nanik Suciati, S.Kom., M.Kom.",
  "Prof. Dr. Eng. Chastine Fatichah, S.Kom., M.Kom.",
  "Prof. Ir. Handayani Tjandrasa, M.Sc., Ph.D.",
  "Prof. Dr. Agus Zainal Arifin, S.Kom., M.Kom.",
  "Dini Adni Navastara, S.Kom., M.Sc.",
  "Dr. Wahyu Suadi, S.Kom, M.Kom.",
  "Dr. Radityo Anggoro, S.Kom., M.Sc.",
  "Prof. Ir. Supeno Djanali, M.Sc Ph.D.",
  "Royyana Muslim Ijtihadie, S.Kom.,M.Kom., Ph.D",
  "Imam Kuswardayan, S.Kom., MT.",
  "Dr. Eng. Darlis Herumurti, S.Kom., M.Kom",
  "Dr. Anny Yuniarti, S.Kom., M.Comp.Sc.",
  "Wijayanti Nurul Khotimah, S.Kom., M.Sc.",
  "Hadziq Fabroyir, S.Kom., Ph.D.",
  "Siska Arifiani, S.Kom., M.Kom.",
  "Dr. Yudhi Purwananto, S.Kom., M.Kom.",
  "Prof. Dr. Diana Purwitasari, S.Kom., M.Sc.",
  "Ir. F.X. Arunanto, M.Sc.",
  "Rully Soelaiman, S.Kom,M.Kom.",
  "Dr. Dwi Sunaryono, S.Kom., M.Kom.",
  "Fajar Baskoro, S.Kom., MT.",
  "Misbakhul Munir Irfan Subakti, S.Kom., M.Sc.",
  "Agus Budi Raharjo, S.Kom., M.Kom., Ph.D.",
  "Prof. Drs. Ec. Ir. Riyanarto Sarno, M.Sc., Ph.D.",
  "Adhatus Solichah Ahmadiyah, S.Kom., M.Sc.",
  "Ratih Nur Esti Anggraini, S.Kom., M.Sc.,Ph.D.",
  "Nurul Fajrin Ariyani, S.Kom., M.Sc.",
  "Abdul Munif, S.Kom., M.Sc.",
  "Shintami Chusnul Hidayati, S.Kom., M.Sc., Ph.D",
  "Kelly Rossa Sungkono, S.Kom., M.Kom.",
  "Victor Hariadi, S.Si., M.Kom.",
  "Prof. Dr. Ir. Joko Lianto Buliali, M.Sc.",
  "Dr. Ahmad Saikhu, S.Si., MT.",
  "Dr. Bilqis Amaliah, S.Kom.,M.Kom.",
  "Arya Yudhi Wijaya, S.Kom, M.Kom.",
];

function autocomplete(inp, arr, loc) {
  var currentFocus;
  inp.addEventListener("input", function (e) {
    var a,
      b,
      i,
      val = this.value;
    closeAllLists();
    if (!val) {
      return false;
    }
    currentFocus = -1;
    a = document.createElement("DIV");
    a.setAttribute("class", "autocomplete-items");
    loc.appendChild(a);
    for (i = 0; i < arr.length; i++) {
      if (arr[i].substr(0, val.length).toUpperCase() == val.toUpperCase()) {
        b = document.createElement("DIV");
        b.innerHTML = "<strong>" + arr[i].substr(0, val.length) + "</strong>";
        b.innerHTML += arr[i].substr(val.length);
        b.innerHTML += "<input type='hidden' value='" + arr[i] + "'>";
        b.addEventListener("click", function (e) {
          inp.value = this.getElementsByTagName("input")[0].value;
          closeAllLists();
        });
        a.appendChild(b);
      }
    }
  });
  inp.addEventListener("keydown", function (e) {
    var x = document.getElementById(this.id + "autocomplete-list");
    if (x) x = x.getElementsByTagName("div");
    if (e.keyCode == 40) {
      currentFocus++;
      addActive(x);
    } else if (e.keyCode == 38) {
      currentFocus--;
      addActive(x);
    } else if (e.keyCode == 13) {
      e.preventDefault();
      if (currentFocus > -1) {
        if (x) x[currentFocus].click();
      }
    }
  });
  function addActive(x) {
    if (!x) return false;
    removeActive(x);
    if (currentFocus >= x.length) currentFocus = 0;
    if (currentFocus < 0) currentFocus = x.length - 1;
    x[currentFocus].classList.add("autocomplete-active");
  }
  function removeActive(x) {
    for (var i = 0; i < x.length; i++) {
      x[i].classList.remove("autocomplete-active");
    }
  }
  function closeAllLists(elmnt) {
    var x = document.getElementsByClassName("autocomplete-items");
    for (var i = 0; i < x.length; i++) {
      if (elmnt != x[i] && elmnt != inp) {
        x[i].parentNode.removeChild(x[i]);
      }
    }
  }
  document.addEventListener("click", function (e) {
    closeAllLists(e.target);
  });
}

autocomplete(
  document.getElementById("nama"),
  recommendName,
  document.getElementById("suggestion-name")
);
autocomplete(
  document.getElementById("dosen"),
  dosenList,
  document.getElementById("suggestion-dosen")
);
